# 100 ejercicios de numpy

Esta es una colección de ejercicios recogidos de distintas fuentes como: numpy mailing list, stackoverflow Y
documentación de numpy. El objetivo de esta colección es ofrecer material para el aprendizaje de numpy.

Este repositorio es una traducción del español del repositorio original en ingles 
[Respositorio de rougier](https://github.com/rougier/numpy-100).

Archivos generados de manera automática. Vea la documentación para cambiar preguntas/respuestas/ayudas (questions/answers/hints)

Ejecute `initialize.py`, para que puedas consultar la respuesta `answer(n)` y una ayuda
`hint(n)` siendo `n` el número de la pregunta.

In [24]:
"!pip install mdutils"

'!pip install mdutils'

In [25]:
%run initialise.py  



Exception: File `'initialise.py'` not found.

#### 1. Importa el paquete `numpy` como `np` (★☆☆)

In [12]:
import numpy as  np

#### 2. Imprima por pantalla la versión y la configuración de numpy (★☆☆)

In [3]:
np.__version__

'2.2.2'

#### 3. Cree un vector null de tamaño 10 (vector de zeros)(★☆☆)

In [22]:

vector_zeros=np.zeros(10)

print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Como encuentra el tamaño en memoria de un array (★☆☆)

In [23]:
print(vector_zeros.nbytes)

80


#### 5. ¿Cómo obtiene la documentación de numpy desde la terminal (comando de línea)? (★☆☆)

In [24]:
"""
python -m webbrowser -t "https://numpy.org/doc/stable/"
"""


'\npython -m webbrowser -t "https://numpy.org/doc/stable/"\n'

#### 6. Crea un vector de ceros de tamaño 10 cuyo valor en la quinta posición sea 1 (★☆☆)

In [8]:
vector_zeros=[0,0,0,0,0,1,0,0,0,0]
print(vector_zeros)

[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]


#### 7. Crea un vector con sus valores contegan los números del 10 a 49 (★☆☆)

In [12]:
array1= np.arange(10,50)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Obrenga un vector invertido (el primer elemento se convierte en el último) (★☆☆)

In [14]:
vector = np.array([1, 2, 3, 4, 5])

vector_invertido = vector[::-1]
print(vector_invertido)

[5 4 3 2 1]


#### 9. Crea una matriz 3x3 cuyos valores contengan lo números del 0 al 8 (★☆☆)

In [14]:
matriz = np.arange(9).reshape(3, 3)
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Encuentre los elementos cuyos índice no son cero [1,2,0,0,4,0] (★☆☆)

In [15]:
2,0,0,4,0

(2, 0, 0, 4, 0)

#### 11. Crea una matriz identidad de 3x3 (★☆☆)

In [15]:
matriz_idetidad=np.eye(3)
print(matriz_idetidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Crea un vector 3x3x3 con valores aleatorios (★☆☆)

In [20]:
vector=np.random.random((3,3,3))
print(vector)

[[[0.55588252 0.22249296 0.90309463]
  [0.95500343 0.41725201 0.36366208]
  [0.63549609 0.41006906 0.38333616]]

 [[0.20878358 0.9893077  0.82108052]
  [0.7032467  0.04216    0.1428589 ]
  [0.54440635 0.8920809  0.61488842]]

 [[0.04899435 0.13900847 0.79493786]
  [0.638346   0.670356   0.06462857]
  [0.88695835 0.32118002 0.0152969 ]]]


#### 13. Crea una matriz 10x10 con valores random y encuentra el valor máximo yel mínimo (★☆☆)

In [18]:
matrixran=np.random.rand(10,10)
valormax=np.max(matrixran)
valormin=np.min(matrixran)
print(matrixran)
print("valor maximo es:", valormax, "y", "valor minimo es:", valormin)

[[0.62386512 0.61879938 0.23834105 0.22625021 0.15243596 0.22976398
  0.68234512 0.95576295 0.88909172 0.44090308]
 [0.92155668 0.75997319 0.44733177 0.85241184 0.03962624 0.58035772
  0.96990224 0.36321723 0.82045688 0.15030909]
 [0.27911235 0.75283612 0.3869647  0.38547931 0.3176889  0.18654188
  0.86525452 0.66385976 0.47170421 0.38990923]
 [0.78903379 0.30446796 0.05296475 0.79791897 0.05998006 0.21168639
  0.80726758 0.03108787 0.144962   0.22126146]
 [0.14965101 0.69951247 0.45790126 0.07875871 0.95424105 0.42223085
  0.41698142 0.90551958 0.79664458 0.9473108 ]
 [0.63273622 0.92153665 0.86216172 0.72638378 0.52635025 0.34188656
  0.8240675  0.89817234 0.27012595 0.37437831]
 [0.2345273  0.75594235 0.99103429 0.25929862 0.429304   0.04313238
  0.33309987 0.82138388 0.98012634 0.64571853]
 [0.14470306 0.88558432 0.54974623 0.14332799 0.95889713 0.68017273
  0.13764954 0.20892564 0.03445443 0.30748895]
 [0.56944063 0.65361263 0.17213076 0.1631261  0.01484457 0.56100672
  0.10640023

#### 14. Crea un vector de tamaño 30 con valores aleatorios y encuentre el valor promedio (★☆☆)

In [23]:
vector =np.random.random(30)
print(vector)
promedio=np.mean(vector)
print(promedio)

[0.85239916 0.4895842  0.78971158 0.5437703  0.21486725 0.24856876
 0.00165027 0.17887612 0.88666059 0.8780037  0.21021957 0.13058586
 0.72867698 0.60859533 0.98460511 0.55293855 0.17418398 0.08876391
 0.70772819 0.14229677 0.53168138 0.67911538 0.98456065 0.35461144
 0.78947814 0.25885772 0.25205259 0.82092332 0.14402272 0.91460185]
0.5047530451536343


#### 15. Crea un vector 2D con los valores de 1 en el borde (es decir en la primera y última filas y columnas) con valores de 0 en el interior (★☆☆)

In [19]:
vector_2d=np.ones((5,5))
vector_2d[1:-1, 1:-1] = 0
print(vector_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. ¿Cómo añadir un borde (llenado con ceros) a una matriz existente? (★☆☆)

In [26]:
# Crear una matriz de ejemplo 3x3
matriz = np.ones((3, 3))

# Añadir un borde de ceros
matriz_con_borde = np.pad(matriz, pad_width=1, mode='constant', constant_values=0)

print(matriz_con_borde)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. ¿Cuál es el resultado de la siguiente expresión? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
print(0* np.nan)
print(np.nan== np.nan)
print(np.inf >np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3== 3*0.1)

nan
False
False
nan
True
False


#### 18. Crea una matriz 5x5 con valores 1,2,3,4 justo debajo de la diagonal (★☆☆)

In [28]:

matriz = np.zeros((5, 5))
for i in range(4):
    matriz[i+1, i] = i+1 

print(matriz)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Crea una matriz 8x8 y llénelo con un patrón similar al del tablero de ajedrez (★☆☆)

In [40]:
matajedrez=np.ones((8,8))
matajedrez[::2, ::2] = 0
matajedrez[1::2, 1::2]=0
print(matajedrez)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Considere un array de dimensiones (6,7,8), ¿Cuáles son los índices (x,y,z) del 100vo elemento? (★☆☆)

In [43]:

array =np.random.random((6, 7, 8)) 
print(array)         
valor100= array.ravel()[100]
print (valor100)


indices = np.unravel_index(100, (6,7,8))
print(indices)


[[[0.3527004  0.57739964 0.76416547 0.07591075 0.08268764 0.58077214
   0.13148096 0.62449605]
  [0.83165809 0.69010874 0.56876822 0.76872105 0.8964582  0.20186559
   0.34676028 0.34916568]
  [0.27127649 0.25633577 0.34459908 0.2453813  0.75122651 0.77472886
   0.47206144 0.89214338]
  [0.38637862 0.43889427 0.56126145 0.60994733 0.73453331 0.69484707
   0.32260729 0.76316763]
  [0.55589963 0.58234541 0.42233578 0.42819708 0.74961462 0.59151103
   0.13269152 0.20120029]
  [0.0169467  0.18016421 0.77484484 0.79749839 0.04306389 0.36084144
   0.15744237 0.50956363]
  [0.67851155 0.31687048 0.04581697 0.37288083 0.46045204 0.84946449
   0.31910628 0.01188802]]

 [[0.5430544  0.78761557 0.39611214 0.15031936 0.43820955 0.25016053
   0.89036664 0.91828093]
  [0.57511969 0.1076817  0.24553682 0.38447615 0.70212805 0.5364851
   0.98321976 0.1742237 ]
  [0.4080253  0.71732814 0.15639174 0.89928494 0.57734031 0.92550548
   0.34582615 0.12896687]
  [0.64744111 0.61990437 0.62444421 0.39451695 0.

#### 21. Cree algo similar a un tablero de ajedez usando la función `tile` (★☆☆)

In [41]:

patron = np.array([[1, 0], [0, 1]])
tabla= np.tile(patron, (4, 4))

print(tabla)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalice una matriz de 5x5 que contiene valores aleatorios (normalize los elementos usando la fórmula z-score) (★☆☆)

In [44]:

matrix = np.random.random((5, 5))


mean = np.mean(matrix)
std_dev = np.std(matrix)

normalized_matrix = (matrix - mean) / std_dev

print("Matriz original:\n", matrix)
print("\nMatriz normalizada (Z-score):\n", normalized_matrix)

Matriz original:
 [[0.52658087 0.04126471 0.4175953  0.14034933 0.98091235]
 [0.02269154 0.03921716 0.69607076 0.33193653 0.26653999]
 [0.82351824 0.45543301 0.1119553  0.4011921  0.12605181]
 [0.36102127 0.82511552 0.84255212 0.63474984 0.81455598]
 [0.97459117 0.69901892 0.44537291 0.502001   0.71633971]]

Matriz normalizada (Z-score):
 [[ 0.13000536 -1.49965857 -0.23596197 -1.16693809  1.65562449]
 [-1.56202621 -1.50653412  0.69914272 -0.52359923 -0.74319706]
 [ 1.12710404 -0.10890509 -1.26228359 -0.29104299 -1.21494832]
 [-0.42593432  1.13246763  1.19101874  0.49323058  1.0970093 ]
 [ 1.63439832  0.70904246 -0.14268634  0.04746756  0.76720469]]


#### 23. Cree un tipo de dato especial (dtype) llamada color que pueda describir el color como cuatro números del tipo unsigned bytes (RGBA) (★☆☆)
Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [42]:

color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
colores = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

print(colores)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiplique una matriz 5x3 y otra 3x2 (producto cruz) (★☆☆)

In [45]:
matrix1= np.random.random((5, 3))
matrix2= np.random.random((3, 2))

result = matrix1.dot(matrix2)

print(result)

[[0.84503921 1.05082537]
 [0.57099535 0.48370841]
 [0.46659523 0.38869356]
 [0.41997956 0.77712537]
 [0.99858088 0.9481459 ]]


#### 25. Dado un array 1D, multiplica por (-1) todos los elementos que esten en el rango 3 a 8 (★☆☆)
Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [43]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr[(arr >= 3) & (arr <= 8)] *= -1

print(arr)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. ¿Cuál es resulatdo de la ejecución del siguiente script? (★☆☆)
```python
# Autor: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [54]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 27. Considere un vector de enteros Z, ¿Cuál de las siguientes expresiones son válidas?
Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [47]:
''''
Z**Z ---- legal
2 << Z >> 2 ----legal 
Z <- Z ---- no legal
1j*Z --- legal
Z/1/1 --- legal
Z<Z>Z --- no legal
'''

"'\nZ**Z ---- legal\n2 << Z >> 2 ----legal \nZ <- Z ---- no legal\n1j*Z --- legal\nZ/1/1 --- legal\nZ<Z>Z --- no legal\n"

#### 28. ¿Cuál es el resultado de las siguientes operaciones? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [55]:

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


C:\Users\natalia\AppData\Local\Temp\ipykernel_14848\2032225821.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\natalia\AppData\Local\Temp\ipykernel_14848\2032225821.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\natalia\AppData\Local\Temp\ipykernel_14848\2032225821.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. ¿Cómo redondear alejado de cero en un vector con valores tipo float? (★☆☆)
Es decir que si n = -0.12  redondear a -1 y si n = 1.2 redondear a 2
How to round away from zero a float array ? (★☆☆)

In [45]:


arr = np.random.uniform(0, 10, size=10)

redondiar = np.copysign(np.ceil(np.abs(arr)), arr)

print(redondiar)


[ 8.  4.  6.  8.  4. 10. 10.  3.  5.  8.]


#### 30. ¿Cómo encontrar valores comunes entre dos vectores? (★☆☆)

In [57]:

vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([4, 5, 6, 7, 8])

comunes = np.intersect1d(vector1, vector2)

print("Valores comunes:", comunes)

Valores comunes: [4 5]


#### 31. ¿Cómo ignorar todos los mensajes de warning de numpy (no recomendado)? (★☆☆)

In [46]:
import warnings
warnings.filterwarnings('ignore')

#### 32. ¿Es la siguiente expresión verdadera (True)? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [60]:
answer= np.sqrt(-1) == np.emath.sqrt(-1)
print(answer)

False


C:\Users\natalia\AppData\Local\Temp\ipykernel_14848\1428784992.py:1: RuntimeWarning: invalid value encountered in sqrt
  answer= np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. ¿Cómo obtener las fechas de ayer, hoy y mañana? (★☆☆)

In [48]:
from datetime import datetime, timedelta

hoy = datetime.today()

ayer = hoy - timedelta(days=1)
mañana = hoy + timedelta(days=1)

print("Ayer:", ayer.strftime('%Y-%m-%d'))
print("Hoy:", hoy.strftime('%Y-%m-%d'))
print("Mañana:", mañana.strftime('%Y-%m-%d'))


Ayer: 2025-01-29
Hoy: 2025-01-30
Mañana: 2025-01-31


#### 34. ¿Cómo obtener todas la fechas correspondientes al mes de Julio del 2016? (★★☆)

In [61]:
fechas = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(fechas)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. ¿Cómo calcular ((A+B)*(-A/2)) (sin usar la función `copy`)?
How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [49]:
A = 10  
B = 5   

resultado = (A + B) * (-A / 2)

print(resultado)


-75.0


#### 36. Extraiga la parte entera de valores positivos de un vector que contenga valores aleatorios, usando 4 diferentes métodos (★★☆)
Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [72]:
integerPart= np.floor(1.5)
print(integerPart)

integerpart2=np.fix(1.5) 
print(integerpart2)

integerpart3=np.int_(1.5)
print(integerpart3)

integerPart4=np.trunc(1.5)
print(integerPart4)



1.0
1.0
1
1.0


#### 37. Crea una matriz 5x5 con sus valores dentro del rango 0 - 4 (★★☆)
Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [53]:
matrizrango=np.random.randint(0,5, size=(5,5))
print(matrizrango)

[[2 2 4 4 1]
 [4 2 2 0 0]
 [1 0 1 3 2]
 [2 4 3 3 4]
 [1 0 2 2 0]]


#### 38. Cree una función que use "yield" para obtener 10 números enteros y use la función para construir un array(★☆☆)
Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [75]:
def generar_enteros():
    for i in range(10):
        yield i  


array = np.array([num for num in generar_enteros()])


print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Cree un vector de tamaño 10 con los valores en el rango 0 a 1 (0 y 1 excluidos). (★★☆)

In [54]:
vectortime = np.random.uniform(0, 1, 10)
print(vectortime)


[0.4735968  0.4419702  0.55882604 0.27128582 0.66325191 0.66293095
 0.32542338 0.31107458 0.62969909 0.47187401]


#### 40. Cree un vector de tamaño 10 con valores aleatorios, luego ordénelos (★★☆).

In [82]:
vector=np.random.uniform(0, 1, 10)

print(vector)
vectorsort=np.sort(vector)
print(vectorsort)

[0.95331979 0.64455076 0.62545196 0.65024605 0.59808926 0.86809625
 0.63981641 0.22489502 0.29063936 0.99495707]
[0.22489502 0.29063936 0.59808926 0.62545196 0.63981641 0.64455076
 0.65024605 0.86809625 0.95331979 0.99495707]


#### 41. ¿Cómo se sumaría un pequeño vector de manera que lo haga más rapidamente que usando la función np.sum? (★★☆)

In [55]:
vector = np.random.uniform(0, 1, 10)
suma = vector @ np.ones(len(vector))  

print(suma)


3.0979318860067275


#### 42. Considere 2 vectores A y B ¿Cómo verifica que son iguales? (★★☆)
Consider two random array A and B, check if they are equal

In [84]:
vectorA=[1,2,3,4,5]
vectorB=[1,2,3,4,5]
equal=np.allclose(vectorA,vectorB)
print(equal)

True


#### 43. Cree un vector inmutable (de sólo lectura) (★★☆)
Make an array immutable (read-only)

In [57]:
arr = (1, 2, 3, 4, 5) 
print(arr)


(1, 2, 3, 4, 5)


#### 44. Cree una maetriz 10x2 con elementos aleatorios,representando coordenadas cartesianas, conviertalas a coordenadas polares (★★☆).

In [86]:
matriz=np.random.random((10,2))
x=matriz[:,0]
y=matriz[:,1]

r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)

print(r)
print(t)    

[0.53050912 1.09852906 0.80577867 0.94697555 0.79502813 0.83663083
 0.59140111 1.27520427 0.21087437 1.12045695]
[1.23599834 0.9066308  0.60259625 0.20198984 0.20061317 1.52222239
 1.54064023 0.78409779 0.26441455 0.84554779]


#### 45. Crea un vector con 10 elementos aleatorios y reemplace el valor máximo con 0 (★★☆)

In [60]:
vector = np.random.randint(1, 101, size=10)
print("Vector original:", vector)
max_index = np.argmax(vector)
vector[max_index] = 0
print("Vector modificado:", vector)


Vector original: [75 89 63 68 55 25 55 58 50 49]
Vector modificado: [75  0 63 68 55 25 55 58 50 49]


#### 46. Crea un vector structurado (structured array) con `x` e `y` como coordenadas, que generen un grilla (meshgrid) en el área [0, 1]x[0, 1] (★★☆)
Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [87]:

resolucion = 5

x = np.linspace(0, 1, resolucion)
y = np.linspace(0, 1, resolucion)

X, Y = np.meshgrid(x, y)

dtype = [('x', float), ('y', float)]
mesh_array = np.array(list(zip(X.ravel(), Y.ravel())), dtype=dtype)


print(mesh_array)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


#### 47. Dados dos vectores, X, e Y, construya la matriz de Cauchy C (Cij =1/(xi - yj)) (★★☆)

In [3]:
def matriz_cauchy(X, Y):
    X = np.array(X, dtype=float)
    Y = np.array(Y, dtype=float)

    if len(X) != len(Y):
        raise ValueError("Los vectores X e Y deben tener la misma longitud")

    C = 1 / (X[:, np.newaxis] - Y) 
    return C


X = [1, 2, 3]
Y = [4, 5, 6]
C = matriz_cauchy(X, Y)
print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Imprima el máximo y mínimo valor representable para un tipo de datos de numpy escalar (★★☆)

In [88]:

finfo = np.finfo(np.float64)
print(f"Máximo valor de float64: {finfo.max}")
print(f"Mínimo valor de float64: {finfo.min}")


iinfo = np.iinfo(np.int32)
print(f"Máximo valor de int32: {iinfo.max}")
print(f"Mínimo valor de int32: {iinfo.min}")

Máximo valor de float64: 1.7976931348623157e+308
Mínimo valor de float64: -1.7976931348623157e+308
Máximo valor de int32: 2147483647
Mínimo valor de int32: -2147483648


#### 49. ¿Cómo imprimir todos los valores de un vector? (★★☆)
(Recuerde que cuando el vector es muy grade numpy suele mostrarlos en secciones o sólo una parte)

In [ ]:
vector = [1, 2, 3, 4, 5]
print(vector) 


#### 50. ¿Cómo encontrar el valor más cercano a un valor(valor escalar) en un vector? (★★☆)

In [92]:

vector = np.array([1, 3, 7, 15, 9, 2])
print(vector)


valor = 19

diferencias = np.abs(vector - valor)

indice_cercano = np.argmin(diferencias)

valor_cercano = vector[indice_cercano]

print(f"El valor más cercano a {valor} en el vector es {valor_cercano} ")


[ 1  3  7 15  9  2]
El valor más cercano a 19 en el vector es 15 


#### 51. Crea un vector estructurada (structured array) representado la posición (x, y) y el color (r, g, b) (★★☆)

In [4]:
dtype = np.dtype([('pos', [('x', 'f4'), ('y', 'f4')]),  
                  ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])]) 

vector = np.array([((10.5, 20.0), (255, 0, 0)), 
                   ((5.2, 15.3), (0, 255, 0)),   
                   ((8.7, 12.1), (0, 0, 255))],  
                 dtype=dtype)

print("Primer elemento:", vector[0])
print("Posición del segundo elemento:", vector[1]['pos'])
print("Color del tercer elemento:", vector[2]['color'])


Primer elemento: ((10.5, 20.0), (255, 0, 0))
Posición del segundo elemento: (5.2, 15.3)
Color del tercer elemento: (0, 0, 255)


#### 52. Considere un vector de elementos aleatorios, de dimensiones 100x2, representado coordenadas (x, y), encuentre las distancias de entre todos los puntos en una matriz 100x100 (★★☆)

In [96]:

puntos = np.random.rand(100, 2) * 10

distancias = np.zeros((100, 100))

for i in range(100):
    for j in range(100):
        distancias[i, j] = np.linalg.norm(puntos[i] - puntos[j])


print(distancias)


[[0.         4.19188724 5.74008997 ... 4.95717184 3.85123934 6.01062909]
 [4.19188724 0.         5.90939771 ... 2.91086981 8.03601238 6.05980467]
 [5.74008997 5.90939771 0.         ... 3.31970237 7.6514179  0.28197285]
 ...
 [4.95717184 2.91086981 3.31970237 ... 0.         8.26739182 3.39814423]
 [3.85123934 8.03601238 7.6514179  ... 8.26739182 0.         7.92698532]
 [6.01062909 6.05980467 0.28197285 ... 3.39814423 7.92698532 0.        ]]


#### 53. ¿Cómo convertir un vector de float(32 bits) a un vector entero (32 bits) ?

In [3]:
vectorfloat = np.array([1.7, 2.3, -3.8, 4.9, 5.2], dtype=np.float32)
vectorint=vectorfloat.astype(np.int32)
print(vectorint)

[ 1  2 -3  4  5]


#### 54. ¿Cómo podrías convertir el siguiente texto en una matriz de numpy? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [98]:

texto = """
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
"""


matriz = np.array([
    [float(num) if num.strip() else np.nan for num in linea.split(",")]
    for linea in texto.strip().split("\n")
])


print(matriz)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. ¿Cuál es el equivalente de la función `enumerate` para vectores numpy? (★★☆)

In [99]:
vector = np.array([10, 20, 30, 40])

for idx, value in np.ndenumerate(vector):
    print(f"Índice: {idx[0]}, Valor: {value}")


Índice: 0, Valor: 10
Índice: 1, Valor: 20
Índice: 2, Valor: 30
Índice: 3, Valor: 40


#### 56. Genera una matriz 2d tipo campana de Gauss (sigma = 1, mu = 0) (2D Gaussian-like array) (★★☆)

In [103]:

size = 10  
sd = 1   
    

x = np.linspace(-3, 3, size)
y = np.linspace(-3, 3, size)
X, Y = np.meshgrid(x, y)


G = np.exp(-(X**2 + Y**2) / (2 * sd**2))

print(G)

[[1.23409804e-04 7.30177997e-04 2.77005282e-03 6.73794700e-03
  1.05086605e-02 1.05086605e-02 6.73794700e-03 2.77005282e-03
  7.30177997e-04 1.23409804e-04]
 [7.30177997e-04 4.32023947e-03 1.63895538e-02 3.98663678e-02
  6.21765240e-02 6.21765240e-02 3.98663678e-02 1.63895538e-02
  4.32023947e-03 7.30177997e-04]
 [2.77005282e-03 1.63895538e-02 6.21765240e-02 1.51239760e-01
  2.35877083e-01 2.35877083e-01 1.51239760e-01 6.21765240e-02
  1.63895538e-02 2.77005282e-03]
 [6.73794700e-03 3.98663678e-02 1.51239760e-01 3.67879441e-01
  5.73753421e-01 5.73753421e-01 3.67879441e-01 1.51239760e-01
  3.98663678e-02 6.73794700e-03]
 [1.05086605e-02 6.21765240e-02 2.35877083e-01 5.73753421e-01
  8.94839317e-01 8.94839317e-01 5.73753421e-01 2.35877083e-01
  6.21765240e-02 1.05086605e-02]
 [1.05086605e-02 6.21765240e-02 2.35877083e-01 5.73753421e-01
  8.94839317e-01 8.94839317e-01 5.73753421e-01 2.35877083e-01
  6.21765240e-02 1.05086605e-02]
 [6.73794700e-03 3.98663678e-02 1.51239760e-01 3.67879441e

#### 57. ¿Cómo poner aleatoriamente p elementos en un array 2d? (★★☆)

In [6]:
filas, columnas = 5, 5
p = 5  
array = np.zeros((filas, columnas), dtype=int)
indices = np.random.choice(filas * columnas, p, replace=False)
fila_idx, col_idx = np.unravel_index(indices, (filas, columnas))

array[fila_idx, col_idx] = 1

print(array)


[[1 0 0 0 0]
 [1 0 1 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


#### 58. Dada una matriz, resta a cada elemento de una fila el promedio de la fila (★★☆)
Subtract the mean of each row of a matrix (★★☆)

In [106]:

A = np.random.randint(1, 10, (5, 5))
print("Matriz original:\n", A)

row_means = A.mean(axis=1, keepdims=True)

A_centered = A - row_means

print("\nMatriz con el promedio restado por fila:\n", A_centered)


Matriz original:
 [[5 1 2 4 1]
 [9 3 2 4 6]
 [2 9 8 1 1]
 [8 4 2 9 9]
 [3 7 8 9 6]]

Matriz con el promedio restado por fila:
 [[ 2.4 -1.6 -0.6  1.4 -1.6]
 [ 4.2 -1.8 -2.8 -0.8  1.2]
 [-2.2  4.8  3.8 -3.2 -3.2]
 [ 1.6 -2.4 -4.4  2.6  2.6]
 [-3.6  0.4  1.4  2.4 -0.6]]


#### 59. ¿Cómo ordenar una matriz teniendo como referencia la n ava columna? (★★☆)
How to sort an array by the nth column? (★★☆)

In [8]:
matriz = np.array([
    [3, 2, 5],
    [1, 4, 2],
    [7, 1, 3]
])
n = 1  
matriz_ordenada = matriz[matriz[:, n].argsort()]

print(matriz_ordenada)


[[7 1 3]
 [3 2 5]
 [1 4 2]]


#### 60. ¿Cómo averiguar si una matriz tiene columnas nulas? (★★☆)

In [107]:

A = np.array([
    [0, 2, 3, 0],
    [0, 5, 6, 0],
    [0, 8, 9, 0]
])

is_null_column = np.all(A == 0, axis=0)

print("Matriz original:\n", A)
print("\nColumnas nulas (True = columna nula):\n", is_null_column)


null_column_indices = np.where(is_null_column)[0]
print("\nÍndices de las columnas nulas:", null_column_indices)


Matriz original:
 [[0 2 3 0]
 [0 5 6 0]
 [0 8 9 0]]

Columnas nulas (True = columna nula):
 [ True False False  True]

Índices de las columnas nulas: [0 3]


#### 61. Encuentre el valor más cercano a un valor dado en un vector (★★☆)

In [9]:
vector = np.array([10, 20, 35, 50, 65, 80])
valor_dado = 38
indice_cercano = np.abs(vector - valor_dado).argmin()
valor_mas_cercano = vector[indice_cercano]

print(f"El valor más cercano a {valor_dado} es {valor_mas_cercano}")


El valor más cercano a 38 es 35


#### 62. Considere 2 arrays con dimensiones (1, 3) y (3, 1), ¿Cómo calcular su suma usando un iterador? (★★☆)
Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Crea un clase vector (vector class) que tenga name como atributo (★★☆)
Create an array class that has a name attribute (★★☆)

In [ ]:
class Vector:
    def __init__(self, name, values):
        self.name = name
        self.values = list(values) 
    def __repr__(self):
        return f"Vector('{self.name}', {self.values})"

    def magnitude(self):
        return sum(x**2 for x in self.values) ** 0.5

    def normalize(self):
        mag = self.magnitude()
        if mag == 0:
            return Vector(self.name + "_norm", [0] * len(self.values))
        return Vector(self.name + "_norm", [x / mag for x in self.values])
    
    def dot(self, other):
        """ Calcula el producto punto con otro vector. """
        if len(self.values) != len(other.values):
            raise ValueError("Los vectores deben tener la misma dimensión.")
        return sum(x * y for x, y in zip(self.values, other.values))


#### 64. Dado un vector Z, ¿Cómo añadir 1 a cada elemento en las posiciones dadas por otro vector I? (tenga cuidado con los índices repetidos) (★★★)
Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. ¿Cómo acumular (sumar) los elementos de un vector X en un vector F de acuerdo a un vector de posiciones I? (★★★)
```python
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
# Resultado F = [0, 7, 0, 6, 5, 0, 0, 0, 0, 3]
```

In [10]:
X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([1, 3, 9, 3, 4, 1])
F = np.zeros(I.max() + 1, dtype=int)
np.add.at(F, I, X)
print(F) 


[0 7 0 6 5 0 0 0 0 3]


#### 66. Considere un numpy array de dimensiones (w, h, 3) que representa una imagen, calcule el número de colores únicos (★★☆)
Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considere un array de 4 dimensiones, ¿Cómo obtener la suma de las dos últimas dimensiones ó ejes? (★★★)
Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [12]:
A = np.random.randint(1, 10, (2, 3, 4, 5))
resultado = np.sum(A, axis=(-2, -1))

print("Forma original del array:", A.shape) 
print("Resultado después de sumar:", resultado.shape)  
print(resultado)


Forma original del array: (2, 3, 4, 5)
Resultado después de sumar: (2, 3)
[[100 105  98]
 [125 113 104]]


#### 68. Considere un vector unidimensional D, ¿cómo calcular los promedios de los subsets de D, si se tienen un vector S del mismo tamaño describiendo los índices de las posiciones de las cuáles deben obtenerse los promedios?(★★★)
```python
# Sea por ejemplo D
D = [0.3, 0.5, 0.2, 0.7, 1., -0.6]
# y S
S = [0, 1, 1, 2, 2, 2]
# El vector de los promedios será
R = [0.3, 0.35, 0.36667]
```

#### 69. ¿Cómo obtener la diagonal de una matriz que es resultado de la operación entre dos matrices `np.dot(A, B)`? Use las matrices A y B para su respuesta.(★★★)

In [13]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
diag1 = np.diag(np.dot(A, B))
diag2 = np.einsum('ij,ji->i', A, B)
diag3 = np.sum(A * B.T, axis=1)

print("Diagonal con np.dot y np.diag:", diag1)
print("Diagonal con np.einsum:", diag2)
print("Diagonal con sum y multiplicación:", diag3)


Diagonal con np.dot y np.diag: [30 69 90]
Diagonal con np.einsum: [30 69 90]
Diagonal con sum y multiplicación: [30 69 90]


#### 70. Sea el vector [1, 2, 3, 4, 5], ¿Cómo construir un nuevo vector con 3 consecutivos zeros intercalados entre cada valor?  (★★★)
Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Sea un arrays de dimensiones (5, 5, 3), cómo multiplicarlo por un array de dimensiones (5, 5)? (★★★)

In [14]:
vector_float = np.array([1.7, 2.3, -3.8, 4.9], dtype=np.float32)
vector_int = vector_float.astype(np.int32)

print(vector_int)


[ 1  2 -3  4]


#### 72. ¿Cómo intercambiar dos filas en un array? (★★★)

#### 73. Sea un set de tripletes describiendo 10 triangulos (con lados compartidos), encuentre el set de las líneas que componen todos lo triangulos. (★★★)
Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Dado un array ordenado C que corresponde a el resultado de un bitcount, ¿cómo producir un array A tal que np.bincount(A) = C ? (★★★)

#### 75. ¿Cómo calcular los promedios de rango variable sobre un array? (★★★)
```python
# Sea
Z = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Sus promedios en un rango de n = 3
[1, 2, 3, 4, 5, 6, 7, 8]
```

#### 76. Sea un vector Z unidimensional, contruya un vector de dos dimensiones (matriz) del cuál su primera fila sea (Z[0],Z[1],Z[2]), su segunda (Z[1],Z[2],Z[3]), es decir que cada siguiente fila empiece con el segundo elementos de la anterior fila, note que (la última fila debería ser (Z[-3],Z[-2],Z[-1]) (★★★)

```python
# Sea Z y R lo que se busca
Z = [0 1 2 3 4]
R = [[0 1 2]
     [1 2 3]
     [2 3 4]]
```

#### 77. ¿Cómo negar un valor boolean, o cambiar el signo de un valor float? (inplace) (★★★)

#### 78. Sean dos sets puntos P0 y P1 tienen el mismo tamaño, el primer punto de P0 describe un línea con el primer punto de P1 y así con todos los elementos de P0 y P1, también se nos da un punto P. 
¿Cómo calcular la distancia del punto P a cada linea que es descrita por los pares de puntos de los sets? (★★★)

#### 79. Sean dos sets puntos P0 y P1 tienen el mismo tamaño, el primer punto de P0 describe un línea con el primer punto de P1 y así con todos los elementos de P0 y P1, también se nos da un set de puntos P. 
¿Cómo calcular la distancia de los puntos  de P a cada linea que es descrita por los pares de puntos de los sets? (★★★)

#### 80. Considere una matriz arbitraria, escriba una función que extraiga una subparte con una forma fija y centrada en un elemento dado (rellene con un 'fill' cuando sea necesario)(★★★)
Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Sea el vector Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], ¿Cómo generar el vector R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Obtenga el rango de un matriz (★★★)

#### 83. ¿Cómo encontrar el valor más frecuente en un array? (★★★)

#### 84. Extraiga todos los bloques contiguos 3x3 de una matriz de elementos aleatorios 10x10 (★★★)
Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Crea un matriz cuya subclase tenga Z[i,j] = Z[j,i] (★★★)
Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consideremos un conjunto de p matrices cuya forma (n,n) y un conjunto de p vectores con forma (n,1). ¿Cómo calcular la suma de los productos de la matriz p a la vez? (el resultado tiene forma (n,1))(★★★)
Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Sea un 16x16 array, ¿cómo obtener la suma en bloques (tamaño del bloque 4x4)? (★★★)

#### 88. ¿Cómo implementar el Juego de la Vida usando numpy arrays? (★★★)
Juego de la Vida (Game Life)
Se trata de un juego de cero jugadores, lo que quiere decir que su evolución está determinada por el estado inicial y no necesita ninguna entrada de datos posterior. El "tablero de juego" es una malla plana formada por cuadrados (las "células") que se extiende por el infinito en todas las direcciones. Por tanto, cada célula tiene 8 células "vecinas", que son las que están próximas a ella, incluidas las diagonales. Las células tienen dos estados: están "vivas" o "muertas" (o "encendidas" y "apagadas"). El estado de las células evoluciona a lo largo de unidades de tiempo discretas (se podría decir que por turnos). El estado de todas las células se tiene en cuenta para calcular el estado de las mismas al turno siguiente. Todas las células se actualizan simultáneamente en cada turno, siguiendo estas reglas:
    Nace: Si una célula muerta tiene exactamente 3 células vecinas vivas "nace" (es decir, al turno siguiente estará viva).
    Muere: una célula viva puede morir por uno de 2 casos:
        Sobrepoblación: si tiene más de tres vecinos alrededor.
        Aislamiento: si tiene solo un vecino alrededor o ninguno.
    Vive: una célula se mantiene viva si tiene 2 o 3 vecinos a su alrededor.

#### 89. ¿Cómo obtener el enésimo (n-avo) valor más grande de un vector? (★★★)

#### 90. Dado un arbitrario número de vectores, contruya el producto cartesiano (la combinación de cada elemento con todos lo elementos) (★★★)

#### 91. ¿Cómo crear un registro a partir de un arrys normal? (★★★)
How to create a record array from a regular array? (★★★)

#### 92. Dado un vector muy largo Z, calcule Z elevado a la potencia 3 usando 3 diferentes métodos (★★★)

#### 93. Dados dos arrays A y B de tamaños (8, 3) y (2, 2) repectivamente. Cómo encontrar las fila de A que contengan elementos de cada fila de B 
Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Dada una matriz 10x3, extraiga las filas con valores no iguales (Ejemplo [2,2,3]) (★★★)

#### 95. Convierta un vector de enteros a una matriz que represente los enteros en binario (★★★)
Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Dadas dos matrices, ¿Cómo extraer filas que sean únicas? (★★★)
Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considere dos vectores A y B, escriba usando `eisum` el equivalente de las funciones `inner`, `sum`, `outer` y `mul` (★★★)
Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considere un camino descrito por dos vectores (X,Y), ¿Cómo tomar muestras del mismo usando muestras equidistantes? (★★★)
Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Dado un entero n y una matriz X, seleccione de X las filas que pueden ser interpretadas como extraídas de una distribución multinomial con n grados.
Es decir las filas que contengan enteros y que suman n. (★★★)
Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, 
i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Calcule con un intervalo de confianza del 95% el promedio de un vector X.
(es decir, volver a muestrear los elementos ddel vector N veces, calcular la media de cada muestra y luego calcular percentiles sobre los promedios). (★★★)
Compute bootstrapped 95% confidence intervals for the mean of a 1D array X 
(i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)